from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


class PaperService:
    """
    Orchestrates all question-paper operations.

    Responsibilities (SRP):
        - Coordinating the paper generation pipeline only.
        - Delegates: file I/O → :class:`~infrastructure.file_service.FileService`,
          question selection → :class:`~core.question_strategy.QuestionStrategy`,
          persistence → :class:`~repositories.paper_repository.PaperRepository`.

    Design patterns:
        - **Dependency Injection**: all collaborators are injected via
          the constructor — no hard-coded instantiation anywhere.
        - **Strategy**: question formatting is fully delegated to
          ``question_strategy``, which can be swapped without touching this class.
    """

    def __init__(
        self,
        paper_repo,
        subject_repo,
        extractor,
        analyzer,
        classifier,
        pdf_gen,
        file_service,
        question_strategy,
    ):
        """
        Args:
            paper_repo:        :class:`~repositories.paper_repository.PaperRepository`
            subject_repo:      :class:`~repositories.subject_repository.SubjectRepository`
            extractor:         :class:`~core.text_extractor.TextExtractor`
            analyzer:          :class:`~core.nlp_analyzer.NLPAnalyzer`
            classifier:        :class:`~core.bloom_classifier.BloomClassifier`
            pdf_gen:           :class:`~core.pdf_generator.PDFGenerator`
            file_service:      :class:`~infrastructure.file_service.FileService`
            question_strategy: :class:`~core.question_strategy.QuestionStrategy`
        """
        self.paper_repo        = paper_repo
        self.subject_repo      = subject_repo
        self.extractor         = extractor
        self.analyzer          = analyzer
        self.classifier        = classifier
        self.pdf_gen           = pdf_gen
        self.file_service      = file_service
        self.question_strategy = question_strategy
        self._analysis_cache: dict = {}

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_papers(self, user_id: int) -> tuple[list, int]:
        """Return all papers generated by ``user_id``."""
        return self.paper_repo.get_all(user_id), 200

    def get_paper_details(self, paper_id: int, user_id: int) -> tuple[dict, int]:
        """
        Fetch full paper content including segmented sections and MCQ options.

        Args:
            paper_id: ID of the paper to retrieve.
            user_id:  ID of the requesting user (ownership check).

        Returns:
            ``(paper_dict, http_status_code)``
        """
        paper = self.paper_repo.get_by_id(paper_id)
        if not paper or paper["user_id"] != user_id:
            return {"error": "Paper not found or unauthorized"}, 404

        questions   = self.paper_repo.get_questions_by_paper_id(paper_id)
        mcqs         = [q for q in questions if q["question_type"] == "MCQ"]
        short_answers = [q for q in questions if q["question_type"] == "Descriptive"]

        if mcqs:
            self._hydrate_mcq_options(mcqs)

        for q in short_answers:
            q["text"] = q["question_text"]

        paper["sections"] = self._segment_sections(mcqs, short_answers)
        return paper, 200

    def get_paper_pdf(self, paper_id: int, user_id: int) -> tuple:
        """
        Build and return a PDF buffer for the given paper.

        Returns:
            ``(BytesIO | None, paper_dict | error_dict, http_status_code)``
        """
        paper, status = self.get_paper_details(paper_id, user_id)
        if status != 200:
            return None, paper, status

        try:
            pdf_buffer = self.pdf_gen.generate_pdf(paper)
            return pdf_buffer, paper, 200
        except Exception as e:
            logger.error(f"PDF generation failed for paper {paper_id}: {e}")
            return None, {"error": f"PDF generation failed: {e}"}, 500

    # ------------------------------------------------------------------
    # Commands
    # ------------------------------------------------------------------

    def generate_paper(self, data: dict) -> tuple[dict, int]:
        """
        Main orchestration flow for AI-driven question-paper generation.

        Steps:
            1. Validate inputs
            2. Resolve subject and locate reference material (FileService)
            3. Extract and analyse text (TextExtractor / NLPAnalyzer) — cached
            4. Select and format questions (QuestionStrategy)
            5. Persist to database (PaperRepository)

        Args:
            data: Dict from the JSON request body, enriched with ``user_id``.

        Returns:
            ``(response_dict, http_status_code)``
        """
        subject_id    = data.get("subject_id")
        topics        = data.get("topics", [])
        blooms        = data.get("blooms", [])
        difficulty    = data.get("difficulty")
        num_questions = int(data.get("num_questions", 10))

        # 1. Validation
        missing = [f for f in ["subject_id", "topics", "blooms", "difficulty"] if not data.get(f)]
        if missing:
            return {"error": f"Missing required fields: {', '.join(missing)}"}, 400

        # 2. Subject & file lookup — uses injected subject_repo (no inline import)
        subject_data = self.subject_repo.get_by_id(subject_id)
        if not subject_data:
            return {"error": "Subject not found"}, 404

        subject_name = subject_data["name"]
        file_path    = self.file_service.get_file_path_for_subject(subject_name)
        if not file_path:
            return {"error": "No reference material found for this subject."}, 500

        # 3. Text extraction & NLP analysis (cached per file path)
        analysis = self._get_analysis(file_path)
        if "error" in analysis:
            return analysis, 500

        # 4. Question selection & formatting (delegated to Strategy)
        selected = self.question_strategy.select_questions(analysis, topics, blooms, num_questions)
        mcqs, short_answers = self.question_strategy.format_paper(
            selected, difficulty, analysis["keywords"]
        )

        # 5. Persistence
        try:
            total_marks = (
                sum(q["marks"] for q in mcqs)
                + sum(q["marks"] for q in short_answers)
            )
            title    = f"{subject_name} {difficulty} Assessment"
            paper_id = self.paper_repo.create_paper(
                data.get("user_id"), subject_id, title, total_marks, "90 Mins", difficulty
            )

            questions_to_save = [
                {**q, "difficulty": difficulty, "type": "MCQ"} for q in mcqs
            ] + [
                {**q, "difficulty": difficulty, "type": "Descriptive"} for q in short_answers
            ]

            self.paper_repo.save_batch_questions(paper_id, questions_to_save)
            return {"message": "Paper generated successfully", "paperId": paper_id}, 201
        except Exception as e:
            logger.error(f"Persistence error for paper generation: {e}")
            return {"error": "Failed to save generated paper"}, 500

    def update_paper_details(self, paper_id: int, data: dict, user_id: int) -> tuple[dict, int]:
        """
        Update metadata (title, marks, difficulty, etc.) for an existing paper.

        Args:
            paper_id: ID of the paper to update.
            data:     Dict of fields to update (unknown keys are ignored).
            user_id:  Requesting user (ownership check).

        Returns:
            ``(response_dict, http_status_code)``
        """
        existing = self.paper_repo.get_by_id(paper_id)
        if not existing or existing["user_id"] != user_id:
            return {"error": "Paper not found or unauthorized"}, 404

        self.paper_repo.update_paper(
            paper_id,
            data.get("subject_id", existing["subject_id"]),
            data.get("title",      existing["title"]),
            data.get("marks",      existing["marks"]),
            data.get("duration",   existing["duration"]),
            data.get("difficulty", existing["difficulty"]),
        )
        return {"message": "Paper updated successfully"}, 200

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _get_analysis(self, file_path: str) -> dict:
        """
        Returns cached NLP analysis for ``file_path``, computing it on first access.
        """
        if file_path in self._analysis_cache:
            logger.debug(f"Analysis cache hit: {file_path}")
            return self._analysis_cache[file_path]

        try:
            raw_text = self.extractor.extract(file_path)
            analysis = self.analyzer.analyze(raw_text, classifier=self.classifier)
            self._analysis_cache[file_path] = analysis
            return analysis
        except Exception as e:
            logger.error(f"Analysis failed for {file_path}: {e}")
            return {"error": "Failed to process reference material"}

    def _hydrate_mcq_options(self, mcqs: list) -> None:
        """Batch-fetches and attaches options to MCQ questions in-place."""
        mcq_ids    = [q["id"] for q in mcqs]
        all_options = self.paper_repo.get_options_by_question_ids(mcq_ids)
        for q in mcqs:
            q["text"] = q["question_text"]
            opts       = all_options.get(q["id"], [])
            q["options"] = (
                [opt["option_text"] for opt in opts]
                if opts
                else ["Option A", "Option B", "Option C", "Option D"]
            )

    def _segment_sections(self, mcqs: list, short_answers: list) -> list:
        """Groups questions into named exam sections."""
        sections = []
        if mcqs:
            sections.append(
                {
                    "name":      "Section A: Multiple Choice Questions",
                    "marks":     sum(q["marks"] for q in mcqs),
                    "questions": mcqs,
                }
            )
        if short_answers:
            sections.append(
                {
                    "name":      "Section B: Short Answer Questions",
                    "marks":     sum(q["marks"] for q in short_answers),
                    "questions": short_answers,
                }
            )
        return sections
